const STORAGE_KEY='dasha_custom_lists_v4'; 
const HISTORY_KEY='dasha_english_history_v1'; 
const CONFIG_KEY='dasha_supabase_config_v1'; 
const DEFAULT_TABLE='daria_word_lists'; 
const DEFAULT_SHARED_ID='daria-main'; 
let uploadTimer=0; 
let uploadPromise=null; let clientPromise=null; 

const originalSetItem=window.localStorage.setItem.bind(window.localStorage); 
function text(value){return String(value?value:'').trim();} 
function readJson(key){try{const raw=window.localStorage.getItem(key);if(raw){return JSON.parse(raw);}return null;}catch(error){return null;}} 
function safeHistoryArray(value){if(Array.isArray(value)){return value;}return [];} 
function normalizePayload(value,bump){let payload={};let updatedAt=0;if(value){if(typeof value==='object'){payload=value;}}updatedAt=Number(payload.updatedAt);if(!Number.isFinite(updatedAt)){updatedAt=0;}if(bump){updatedAt=Date.now();}return {lists:Array.isArray(payload.lists)?payload.lists:[],deletedBuiltins:Array.isArray(payload.deletedBuiltins)?payload.deletedBuiltins:[],history:safeHistoryArray(payload.history),updatedAt:updatedAt};} 
function hasCloudManagedData(payload){if(!payload){return false;}if(Array.isArray(payload.deletedBuiltins)&&payload.deletedBuiltins.length){return true;}if(Array.isArray(payload.history)&&payload.history.length){return true;}if(Array.isArray(payload.lists)){return payload.lists.some(function(item){const source=text(item&&item.source);return source.indexOf('builtin-')!==0;});}return false;} 
function getConfig(){let source=window.DARIA_SUPABASE_CONFIG;if(!source){source=readJson(CONFIG_KEY);}if(!source){return null;}if(typeof source!=='object'){return null;}const url=text(source.url);const anonKey=text(source.anonKey);const table=text(source.table)?text(source.table):DEFAULT_TABLE;const sharedId=text(source.sharedId)?text(source.sharedId):DEFAULT_SHARED_ID;if(!url){return null;}if(!anonKey){return null;}return {url:url,anonKey:anonKey,table:table,sharedId:sharedId};} 
function getLocalPayload(){const base=readJson(STORAGE_KEY);const history=safeHistoryArray(readJson(HISTORY_KEY));let payload=null;if(base){if(typeof base==='object'){payload=normalizePayload(base,false);}}if(!payload){if(!history.length){return null;}payload=normalizePayload({},true);}payload.history=history;return payload;} 
function writeLocalPayload(payload){const normalized=normalizePayload(payload,false);originalSetItem(STORAGE_KEY,JSON.stringify({lists:normalized.lists,deletedBuiltins:normalized.deletedBuiltins,updatedAt:normalized.updatedAt}));originalSetItem(HISTORY_KEY,JSON.stringify(normalized.history));return normalized;}
function markLocalLists(rawValue){let parsed;let current=getLocalPayload();let updatedAt=0;try{parsed=JSON.parse(rawValue);}catch(error){return null;}if(!current){current=normalizePayload({},false);}parsed=normalizePayload(parsed,false);updatedAt=Number(parsed.updatedAt);if(!Number.isFinite(updatedAt)||updatedAt<=0){updatedAt=Number(current.updatedAt);if(!Number.isFinite(updatedAt)||updatedAt<=0){updatedAt=Date.now();}}parsed.updatedAt=updatedAt;parsed.history=current.history;return writeLocalPayload(parsed);} 
function markLocalHistory(rawValue){let parsed;let current=getLocalPayload();try{parsed=JSON.parse(rawValue);}catch(error){return null;}if(!current){current=normalizePayload({},true);}current.history=safeHistoryArray(parsed);current.updatedAt=Date.now();return writeLocalPayload(current);} 
async function ensureClient(){const config=getConfig();if(!config){return null;}if(!clientPromise){clientPromise=import('https://esm.sh/@supabase/supabase-js@2').then(function(mod){return {client:mod.createClient(config.url,config.anonKey),config:config};}).catch(function(error){console.warn('supabase init error',error);clientPromise=null;return null;});}return clientPromise;} 
async function uploadToCloud(){let ready;let localPayload;let response;if(uploadPromise){return uploadPromise;}uploadPromise=(async function(){ready=await ensureClient();localPayload=getLocalPayload();if(!ready){return null;}if(!localPayload){return null;}if(!hasCloudManagedData(localPayload)){return null;}response=await ready.client.from(ready.config.table).upsert({shared_id:ready.config.sharedId,payload:localPayload,updated_at_ms:localPayload.updatedAt},{onConflict:'shared_id'});if(response.error){throw response.error;}return response.data;})().catch(function(error){console.warn('supabase upload error',error);return null;});await uploadPromise;uploadPromise=null;return null;} 
function queueUpload(){if(uploadTimer){window.clearTimeout(uploadTimer);}uploadTimer=window.setTimeout(function(){uploadToCloud();},500);} 
function announceCloud(payload){let lists=[];let history=[];if(payload){if(Array.isArray(payload.lists)){lists=payload.lists;}if(Array.isArray(payload.history)){history=payload.history;}}window.dispatchEvent(new CustomEvent('dcl-cloud-sync',{detail:{listCount:lists.length,historyCount:history.length}}));}
async function hydrateFromCloud(){const ready=await ensureClient();const localPayload=getLocalPayload();let response;let data=null;let remotePayload=null;let remoteUpdatedAt=0;let localMeaningful=false;let remoteMeaningful=false;if(!ready){return null;}response=await ready.client.from(ready.config.table).select('payload,updated_at_ms').eq('shared_id',ready.config.sharedId).maybeSingle();if(response.error){if(response.status!==406){throw response.error;}}if(response.data){data=response.data;}if(data){if(data.payload){remotePayload=normalizePayload(data.payload,false);}}localMeaningful=hasCloudManagedData(localPayload);remoteMeaningful=hasCloudManagedData(remotePayload);if(!remotePayload){if(localPayload&&localMeaningful){await uploadToCloud();}return null;}if(data){remoteUpdatedAt=Number(data.updated_at_ms);}if(!Number.isFinite(remoteUpdatedAt)){remoteUpdatedAt=0;}if(Number(remotePayload.updatedAt)>remoteUpdatedAt){remoteUpdatedAt=Number(remotePayload.updatedAt);}if(!localPayload){writeLocalPayload(remotePayload);return remotePayload;}if(!localMeaningful&&remoteMeaningful){writeLocalPayload(remotePayload);return remotePayload;}if(Number(localPayload.updatedAt)<remoteUpdatedAt){writeLocalPayload(remotePayload);return remotePayload;}if(Number(localPayload.updatedAt)>remoteUpdatedAt){await uploadToCloud();}return localPayload;} 
window.localStorage.setItem=function(key,value){const result=originalSetItem.apply(window.localStorage,arguments);if(key===STORAGE_KEY){if(typeof value==='string'){markLocalLists(value);}queueUpload();}if(key===HISTORY_KEY){if(typeof value==='string'){markLocalHistory(value);}queueUpload();}return result;}; 
async function refreshCloud(){const payload=await hydrateFromCloud();announceCloud(payload);return payload;} 
window.__dclForceCloudPull=refreshCloud; 
window.__dclCloudReady=refreshCloud().catch(function(error){console.warn('supabase hydrate error',error);return null;}); 
document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden'){uploadToCloud();return;}refreshCloud().catch(function(){return null;});}); 
window.addEventListener('focus',function(){refreshCloud().catch(function(){return null;});});window.addEventListener('online',function(){refreshCloud().catch(function(){return null;});}); 
window.setInterval(function(){if(document.visibilityState==='visible'){refreshCloud().catch(function(){return null;});}},4000); 
window.addEventListener('beforeunload',function(){uploadToCloud();});
